// Generated by CoffeeScript 1.7.1
(function() {
  var s;

  s = require('./index');

  exports.basic = function(test) {
    var sman;
    sman = new s.Basic();
    sman.subscribe('test', function(data) {
      test.deepEqual(data, {
        some: 'data'
      });
      return test.done();
    });
    sman.event('test_fail', {
      some: 'otherdata'
    });
    return sman.event('test', {
      some: 'data'
    });
  };

  exports.asyncCallback = function(test) {
    var sman, smanC;
    smanC = s.Core.extend4000(s.asyncCallbackReturnMixin, s.simplestMatcher);
    sman = new smanC();
    sman.subscribe('test', function(data, callback) {
      callback(null, {
        bla: 3
      });
      return void 0;
    });
    sman.subscribe('test', function(data, callback) {
      callback(null, {
        bla: 8
      });
      return void 0;
    });
    sman.subscribe('somethingelse', function(data, callback) {
      test.fail();
      callback(null, {
        bla: 4
      });
      return void 0;
    });
    return sman.eventAsync('test', {
      some: 'data2'
    }, function(err, data) {
      test.deepEqual(data, [
        {
          bla: 3
        }, {
          bla: 8
        }
      ]);
      test.equals(err, null);
      return sman.eventAsync('nosub', {
        some: 'data3'
      }, function(err, data) {
        test.equals(err, null);
        test.deepEqual(data, []);
        return test.done();
      });
    });
  };

  exports.fancy = function(test) {
    var Validator, cnt, sman, v;
    sman = new s.Fancy();
    Validator = require('validator2-extras');
    v = Validator.v;
    sman.subscribe({
      x: v("Number").Length({
        maximum: 8
      }),
      y: "String"
    }, function(data, callback) {
      return callback(null, 666);
    });
    cnt = 0;
    sman.eventAsync('test', function(err, data) {
      cnt++;
      test.equal(err, null);
      return test.deepEqual(data, []);
    });
    sman.eventAsync({
      x: 3,
      y: 'bla'
    }, function(err, data) {
      cnt++;
      test.equal(err, null);
      return test.deepEqual(data, [666]);
    });
    test.equal(cnt, 2);
    return test.done();
  };

}).call(this);
