// Generated by CoffeeScript 1.4.0
(function() {
  var s;

  s = require('./index');

  exports.basic = function(test) {
    var sman;
    sman = new s.Basic();
    sman.subscribe('test', function(data) {
      test.deepEqual(data, {
        some: 'data'
      });
      return test.done();
    });
    sman.event('test_fail', {
      some: 'otherdata'
    });
    return sman.event('test', {
      some: 'data'
    });
  };

}).call(this);
